version: '2.1'

orbs:
  flutter: circleci/flutter@1.1.0
jobs:
  example-job:
    docker:
      # replace with your preferred image
      - image: cimg/base:stable
    steps:
      - flutter/install_android_gradle
workflows:
  example-workflow:
    jobs:
      - example-job